[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:whois-server]
command=python3 /whois-server.py
autostart=true
autorestart=true
stdout_logfile=/var/log/whois.log
stderr_logfile=/var/log/whois.err

[program:web-server]
command=python3 /app/web/server.py
autostart=true
autorestart=true
stdout_logfile=/var/log/web.log
stderr_logfile=/var/log/web.err
directory=/app/web

[program:bind]
command=/usr/sbin/named -4 -g -c /etc/bind/named.conf
autostart=true
autorestart=true
stdout_logfile=/var/log/named.log
stderr_logfile=/var/log/named.err
