options {
    directory "/var/cache/bind";

    recursion yes;
    allow-query { any; };
    allow-transfer { any; };

    # Слушаем ВСЕ интерфейсы
    listen-on port 53 { any; };
    listen-on-v6 { none; }; # Disable IPv6 if not used

    dnssec-validation no;
};

zone "corp.local" {
    type master;
    file "/etc/bind/zones/corp.local.zone";
};

zone "internal.local" {
    type master;
    file "/etc/bind/zones/internal.local.zone";
    allow-transfer { none; };  # AXFR запрещён
};

zone "200.168.192.in-addr.arpa" {
    type master;
    file "/etc/bind/zones/200.168.192.in-addr.arpa.zone";
};
